### ISSUE TITLE
fix: Resolve TypeScript build errors in browser-automation package

### ISSUE THREAD

**Issue by ojfbot** [ojfbot/cv-builder#63]
## Problem

The `@cv-builder/browser-automation` package has TypeScript compilation errors that prevent `pnpm build` from succeeding, though runtime execution via `tsx` works fine.

**Identified in:** PR #62 (pr-educator analysis)  
**Impact:** Non-blocking for runtime, but blocks clean builds

### 1. Missing DOM Type Definitions (browser.ts)

**File:** `packages/browser-automation/src/automation/browser.ts`

**Errors:**
```
src/automation/browser.ts(66,8): error TS2304: Cannot find name 'window'.
src/automation/browser.ts(331,15): error TS2304: Cannot find name 'window'.
src/automation/browser.ts(332,37): error TS2304: Cannot find name 'indexedDB'.
src/automation/browser.ts(433,10): error TS2304: Cannot find name 'window'.
```

**Root Cause:** Missing DOM types for browser globals (window, indexedDB)

**Solution:**
Add to `tsconfig.json`:
```json
{
  "compilerOptions": {
    "lib": ["ES2022", "DOM"],
    "types": ["node"]
  }
}
```

Or add explicit type imports:
```typescript
/// <reference lib="dom" />
```

### 2. Missing Jest Type Definitions (github/__tests__/*.test.ts)

**Files:** 
- `packages/browser-automation/src/github/__tests__/client.test.ts`
- `packages/browser-automation/src/github/__tests__/service.test.ts`

**Errors:**
```
error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? 
Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
error TS2304: Cannot find name 'expect'.
error TS2304: Cannot find name 'beforeEach'.
error TS2304: Cannot find name 'jest'.
```

**Root Cause:** Jest test files exist but `@types/jest` not installed

**Solution Option 1 (Install Jest Types):**
```bash
cd packages/browser-automation
pnpm add -D @types/jest
```

Update `tsconfig.json`:
```json
{
  "compilerOptions": {
    "types": ["node", "jest"]
  }
}
```

**Solution Option 2 (Remove Jest Tests):**
If these tests are legacy/unused:
```bash
rm -rf packages/browser-automation/src/github/__tests__/
```

### 3. Implicit 'any' Types

**Errors:**
```
src/automation/browser.ts(337,26): error TS7006: Parameter 'db' implicitly has an 'any' type.
src/automation/browser.ts(338,23): error TS7006: Parameter 'db' implicitly has an 'any' type.
```

**Solution:**
Add explicit types:
```typescript
// Before
onsuccess: (db) => resolve(db),
onerror: (db) => reject(db),

// After
onsuccess: (db: IDBDatabase) => resolve(db),
onerror: (error: Event) => reject(error),
```

## Verification

After fixes, run:
```bash
# Type check should pass
pnpm --filter @cv-builder/browser-automation type-check

# Build should succeed
pnpm --filter @cv-builder/browser-automation build

# Ensure runtime still works
pnpm --filter @cv-builder/browser-automation test:visual
```

## Notes

- These errors are **pre-existing** (not introduced by PR #62)
- Runtime execution works fine via `tsx` (TypeScript execution)
- Errors only appear during `tsc --noEmit` compilation
- Should be fixed in separate PR to keep PR #62 focused on visual regression

## Acceptance Criteria

- [ ] All TypeScript compilation errors resolved
- [ ] `pnpm type-check` passes for browser-automation package
- [ ] `pnpm build` succeeds for browser-automation package
- [ ] Runtime tests still pass (`pnpm test:visual`)
- [ ] No new TypeScript errors introduced

## Priority

**Medium** - Non-blocking for PR #62 merge, but should be addressed for clean builds

---

**Related:** PR #62 (Visual Regression Testing)  
**Identified By:** pr-educator analysis
